app:
  image: ibmcom/swift-ubuntu:3.1
  ports:
    - "8080:8080"
  volumes:
    - .:/root/Kitura-Starter
  command: bash -c "cd /root/Kitura-Starter && swift package clean && swift build && swift test && ./.build/debug/Kitura-Starter"