app:
  image: ibmcom/swift-ubuntu:4.0.3
  ports:
    - "8080:8080"
  volumes:
    - .:/CognitiveConcierge
  command: bash -c "cd /CognitiveConcierge && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && ./.build-ubuntu/debug/CognitiveConcierge"
